### ISSUE TITLE
Pomodoro Timer Persistence

### ISSUE THREAD

**Issue by JMortonTan** [NJIT-CODEPATH-SP-2021-PomodoroFriends/PomodoroFriends#2]
* User logs in to access previously defined Pomodoro Timers
Must decide how to store timers and manage storage on local android device.
Sqlite?
Must implement custom datatype and fields similar to one defined in schema.
Such datatype must be ready to convert to upload into server side via API.

**Comment by Gginne** [comment]
IMPLEMENTED TIMER SAVING TO PARSE
https://github.com/NJIT-CODEPATH-SP-2021-PomodoroFriends/PomodoroFriends/pull/12
