### ISSUE TITLE
Timer creation and definition by user

### ISSUE THREAD

**Issue by JMortonTan** [NJIT-CODEPATH-SP-2021-PomodoroFriends/PomodoroFriends#3]
* User can create new Pomodoro Timers based on "productivity time", "break time", and number of repetitions.
User must be able to define and create a Pomodoro timer.
This will henceforth be referred to as 'programming' a timer.

Each timer's programming limits must be universally defined in order to limit complexity.

Suggest: AB pattern where user can program 'A' length, 'B' length and how many repetitions.

**Comment by Gginne** [comment]
IMPLEMENTED TIMER CREATION & SAVING
https://github.com/NJIT-CODEPATH-SP-2021-PomodoroFriends/PomodoroFriends/pull/12
